### ISSUE TITLE
Cleanup fails when using dockerizedPip

### ISSUE THREAD

**Issue by carterqw2** [cfchou/serverless-python-individually#10]
**Problem**
When using the dockerizedPip packaging, the plugin starts docker to install pip dependencies. Since docker runs as root, the owner of the installed packages is also root. On subsequent runs, the plugin fails as it cannot delete files owned by root, cleanup fails and so on.

**Solution**
Change the owner of the installed packages to the owner of the lib folder after the installation.

Hi, @cfchou! Faced this issue today. Fixed here #9

**Comment by cfchou** [comment]
Thanks @carterqw2 

I might have misunderstood you. I tried
```
sls deploy -v --pi-no-cleanup
# sls invoke .... and then deploy again with cleanup enabled
sls deploy -v
```
However, I failed to reproduce the problem(for both python2.7/3.6).
Moreover, I `docker run -it` the lambci container and verified the files were generated and deleted as expected.


I suspect it's not a problem of file permission.
You're right that docker pip installs packages as root but from host's point of view, generated files are owned by whatever user running sls and cleaning up is done by host.
```
# inside container
bash-4.2# ls -al hello/wrap.py
-rw-r--r-- 1 root root 362 Aug 19 01:07 hello/wrap.py

# on the host
$ ls -l hello/wrap.py
-rw-r--r--  1 cfchou  staff   362B 19 Aug 09:07 hello/wrap.py
```

What's you host OS? My host is running macOS. I guess under Linux it's pretty much the same. But I can't say anything about windows due to my lack of knowledge and resource......
If you may, could you copy-paste the error message?

**Comment by carterqw2** [comment]
Thanks, @cfchou!

My host OS is Ubuntu 16.04.
```
$ uname -a
Linux carter-rocket 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Here is my serverless.yml:
```
service: my-service

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  environment: ${file(env.yaml):${self:custom.stage}}
  memorySize: 128
  versionFunctions: false
  timeout: 30

package:
  individually: True
  exclude:
    - "**/*"

functions:
  account:
    handler: account/wrap.handler
    events:
      - http: get account/link
      - http: post account/link
    package:
      include:
        - account/*
        - account/lib/**
        - settings/*

custom:
  stage: ${opt:stage, self:provider.stage}
  pyIndividually:
    cleanup: False
    dockerizedPip: True
    wrap:account: account/handler.handle

plugins:
  - serverless-python-individually
```

When I run `sls deploy` for the first time, it finishes fine and leaves the `lib` folder like that (that's from the host):
```
$ ls -la account/lib/
total 1428
drwxrwxr-x 24 carter carter   4096 Aug 19 14:10 .
drwxrwxr-x  4 carter carter   4096 Aug 19 14:09 ..
drwxr-xr-x  3 root   root     4096 Aug 19 14:10 asn1crypto
drwxr-xr-x  2 root   root     4096 Aug 19 14:10 asn1crypto-0.22.0.dist-info
drwxr-xr-x  2 root   root     4096 Aug 19 14:10 cffi
...
```

Then when I run `sls deploy` next time, I got this error:
```
Serverless: WARNING: Plugin PythonIndividually uses deprecated hook before:deploy:createDeploymentArtifacts
Serverless: WARNING: Plugin PythonIndividually uses deprecated hook after:deploy:createDeploymentArtifacts
Serverless: [pyIndividually] wrapName: wrap
Serverless: [pyIndividually] libSubDir: lib
Serverless: [pyIndividually] cleanup: false
Serverless: [pyIndividually] dockerizedPip: true
Serverless: [pyIndividually] Installing packages for endpoint
Serverless: [pyIndividually] Creating alexabot/wrap.py
Serverless: [pyIndividually] Installing packages for account
Serverless: [pyIndividually] Creating account/wrap.py
 
  Error --------------------------------------------------
 
  EACCES: permission denied, unlink 'account/lib/.libs_cffi_backend/libffi-72499c49.so.6.0.4'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: EACCES: permission denied, unlink 'account/lib/.libs_cffi_backend/libffi-72499c49.so.6.0.4'
    at Error (native)
From previous event:
    at BbPromise.all._.map (/srv/git/alexabot/node_modules/serverless-python-individually/index.js:218:59)
    at arrayMap (/srv/git/alexabot/node_modules/lodash/lodash.js:660:23)
    at Function.map (/srv/git/alexabot/node_modules/lodash/lodash.js:9571:14)
    at PythonIndividually.hard_remove (/srv/git/alexabot/node_modules/serverless-python-individually/index.js:218:28)
    at apply (/srv/git/alexabot/node_modules/lodash/lodash.js:496:27)
    at PythonIndividually.wrapper (/srv/git/alexabot/node_modules/lodash/lodash.js:5356:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at PythonIndividually.work (/srv/git/alexabot/node_modules/serverless-python-individually/index.js:168:8)
From previous event:
    at Object.before:deploy:createDeploymentArtifacts [as hook] (/srv/git/alexabot/node_modules/serverless-python-individually/index.js:378:10)
    at BbPromise.reduce (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.spawn (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:248:17)
    at Deploy.BbPromise.bind.then.then (/srv/git/alexabot/node_modules/serverless/lib/plugins/deploy/deploy.js:101:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/srv/git/alexabot/node_modules/serverless/lib/plugins/deploy/deploy.js:99:10)
    at BbPromise.reduce (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.run (/srv/git/alexabot/node_modules/serverless/lib/classes/PluginManager.js:255:17)
    at variables.populateService.then (/srv/git/alexabot/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/srv/git/alexabot/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/srv/git/alexabot/node_modules/serverless/bin/serverless:39:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.2
     Serverless Version:     1.19.0
```

My Docker version:
```
$ docker --version
Docker version 1.12.6, build 78d1802
```

**Comment by carterqw2** [comment]
Also, found this issue https://github.com/moby/moby/issues/3124. I tried running `docker run -u` and passing `uid` and `guid` of the current user, but it fails to install pip dependencies in some cases.

**Comment by cfchou** [comment]
Right, thanks for the information. My assumption that docker should behave the same on both linux and macOS is wrong :( 

I'll provision a linux box to verify your #9 on Monday before merging it.

A small hiccup:  #9 uses `stat -c %u:%g` but on macOS it's `stat -f`. Fortunately the error message doesn't go to stdout/stderr so the process continues.

**Comment by carterqw2** [comment]
Great! Thanks, @cfchou. Updated #9 to get `uid` and `gid` using  the `os` module, that should be more portable.
